language: node_js
node_js:
- '4'
deploy:
  provider: npm
  email: $EMAIL
  api_key:
    secure: IER6/oqkBoORJ68BffCvZwnQssnQ3sEOAT9H5r38ah/TSlbPB6OjXCdMcBaiBqO1zUXW8ZkJaY6OqBO2xX4osgfc/fZD9lOvuBE2TdRQ8mKhZNAbzfpUienAFEjeYFH+T3Z69zEyGQRrREA00KI7GheB/WNuJK3ArPqfIRy/1ioCg4sa+VHgyhLJAglJCuzmZni4DLr1R3buocCqjRAw42fqUrD/iCNYOU3I439SzXT2a+gIk9MMZxu9JsInBgKqOwjQzGUMqM59w8vVh4sSE+GsZycIkGWecwG7YHB/cUsM9pJ2BHU4csoeU27B8U6fFpnd9VW7RkA+zBheibBz4ws4LuHwkhbmqqrdw0SnZf1OSPvhepLSCSh1zyR+7VafM+M7ZlO/XT9P7kZsAGUl7AV3QDH3hw9Q8P0jQDipMixGGfQSkHUTNcZXYSqBstDYVm+KGs46cy0Z0sy7idRSxzXX/l+axQDfLiA6/qANwBaDtdihHUfYPMamSAEyTOlNZRNi9MmYqaSwx1damn0QxlQpN86japiV4aFR7EDxRabeLo8DZpNZSOAnc8QVfJVbrx7rnm32icQb5DgH1ajO0O2zrhxwfhIVrI9ODTbLxKqAG773dI+TxOXdZPZEBhQfvQTKLg6OlcCBDlhSR1UpoaMq+48FLWQFXZU5lo4KFLU=
  skip_cleanup: true
  on:
    branch: master
    tags: true
env:
  global:
    secure: s6j10HngFDCwENqfsK6AFv1QeL7H7qTQJhCLlQ0KlIjtCxNeRPRGKeLTGxjcSTMiD5YWhp6QBrrEFeH3upvqCQcWI/IQtOG0dfI04EW2aIB/xrw7MF9aTFUmIYraqqFnsehp+7odBP/z7q92oaHdirDtVKMLPl9X1B1rHgRmiQWCvJF9W47Gb62wD0VSwN07hshe9yO9kouV0fthOqU0y/XqTATkXWzEmqbTJs+H6KS6cXYYtd8KoDgHRJDy7ClIdD8jhiPuF339gaG7Yl3lxStIOVAYO+Kxu2+PEVS25UI/JiFvZXHy83FRjsEwJF7b3IN5U2mRe/1StHt5ug9VpgOR82df8whq9xzKmLL5jff2sJuZrrp8n+EB+Hgq/7fU2eXixo3ZFrIFp8jd4EABZdBTtZYrL4VP2ohD5WOWAikHKHFs1ZHJfzNoCeL6+3h7NfD6C1DW0E4J6vuIAflV6+vIc0bX8JI+dV6Vnx0lj7xZyRHlyueXgN3JkbCeNfGXs06BazdAsQSqWkZ0GVMm93xm36ae5aGpAZYZLN1o2wh78BJtNpT9IMU/yUOOv81kmoW2f+6fOtSj3IN8pbpUFDu8Jep5hDz0HD6OoGlihjhDLSdP6kvNzoHdDBs7qsfJoZzPVtd3qIeAWI3n1zQC+vhZpLTPyDjWbmlXtxU0TFY=